---
- name: Get instance ID
  ansible.builtin.uri:
    url: http://169.254.169.254/latest/meta-data/instance-id
    return_content: yes
  register: instance_id_result
  changed_when: false

- name: Get instance Region
  ansible.builtin.uri:
    url: http://169.254.169.254/latest/meta-data/placement/region
    return_content: yes
  register: instance_region_result
  changed_when: false

- name: Get Environment tag
  ansible.builtin.command: >
    aws ec2 describe-instances
    --instance-ids {{ instance_id_result.content }}
    --query "Reservations[*].Instances[*].Tags[?Key=='Environment'].Value"
    --output text
  register: aws_env
  changed_when: false
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    AWS_DEFAULT_REGION: "{{ instance_region_result.content }}"

- name: Set environment facts
  ansible.builtin.set_fact:
    environment_name: "{{ aws_env.stdout }}"
    instance_id: "{{ instance_id_result.content }}"
    instance_region: "{{ instance_region_result.content }}"
