---
- name: Debug hostname configuration
  ansible.builtin.debug:
    msg: "Setting hostname to: {{ desired_hostname }}"
  when: desired_hostname != ""

- name: Set hostname using hostnamectl
  ansible.builtin.command: hostnamectl set-hostname {{ desired_hostname }}
  when: desired_hostname != ""
  changed_when: true

- name: Verify short hostname
  ansible.builtin.command: hostname -s
  register: current_hostname
  changed_when: false

- name: Verify FQDN
  ansible.builtin.command: hostname -f
  register: current_fqdn
  changed_when: false

- name: Debug current hostname configuration
  ansible.builtin.debug:
    msg:
      - "Current short hostname: {{ current_hostname.stdout }}"
      - "Current FQDN: {{ current_fqdn.stdout }}"

- name: Re-gather hostname facts
  ansible.builtin.setup:
    filter: ansible_hostname
