---
- name: Provision Ansible controller with SSH key for remote
  hosts: localhost
  roles:
    - role: companieshouse.general.ssh_key
  vars:
    ssh_key_name: ansible_remote
    ssh_key_vault_path: "{{ vault_base_path }}/aws"

- name: CHIPS E2E configurations
  hosts: aws_ec2
  remote_user: ansible-user
  become: true
  gather_facts: true
  roles:
    - role: instance_facts
    - role: hostname_set
    - role: nfs_mount
    - role: symlinks_ec2-user

